version: '3.8'
services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - db

  redis:
    image: "redis:alpine"

  db:
    image: "postgres:13"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
